### ISSUE TITLE
cellRangeValue

### ISSUE THREAD

**Issue by MedinaGitHub** [vogtb/spreadsheet#2]
Hi!

I have a ask about cell Range Value, ¿i what to put in origin? i try put 'A1'  or anything and not working
 /**
   * Get a range of cells.
   * @param origin - the cell id in A1 notation from which this range is being referenced.
   * @param {string} start - first cell coordinate (in A1 notation) in iteration
   * @param {string} end - final cell coordinate (in A1 notation) in iteration
   * @returns {Array}
   */
  cellRangeValue(origin, start: string, end: string) 

Thanks You

**Comment by vogtb** [comment]
I believe `origin` should be the cell that is calling the range value. If I remember correctly, it's because we need to know the origin so we don't have cyclic-dependencies. 

For example, this:

```
var Sheet = require("js-spreadsheet").Sheet;

var sheet = new Sheet();
sheet.setCell("A1", "10");
sheet.setCell("A2", "14");
sheet.setCell("B1", "=A1:A2");
console.log(sheet.getCell("B1").getValue());
```

would result in this call `cellRangeValue("B1", "A1", "A2")`.

Does that make sense?

**Comment by MedinaGitHub** [comment]
Then, should it be like this cellRangeValue("A1", "A1", "A2") ?  why does not it work D=  

anyway I saw that its implementation does not have the Origin parameter, but still putting only the start and the end throws an error of  id.match is not a function

![image](https://user-images.githubusercontent.com/16387514/53765809-d37e9d00-3eaf-11e9-9fab-71d2cddeb26a.png)

**Comment by vogtb** [comment]
You can't have `cellRangeValue("A1", "A1", "A2")` because then you have a reference cycle. For example, if you go in Excel or Google Spreadsheets and enter `=A1:A2` for cell A1, it throws an error because it's a loop. It tries to look up the value of A1 **for** A1, and it if didn't detect the loop it would continue forever. So `origin` and `start` can not be the same value, and the range `start` to `end` cannot contain the origin value.

When you try to user `fixedCellRangeValue` it won't work they way you're using it because it requires 3 parameters.

**Comment by vogtb** [comment]
Eg: 
<img width="400" alt="screen shot 2019-03-04 at 4 25 35 pm" src="https://user-images.githubusercontent.com/4754727/53767050-2e0cfe80-3e9a-11e9-83e9-6f6a11a3dc1d.png">

**Comment by MedinaGitHub** [comment]
so how do I take all the values ​​of a range? for example from A1 to A2

**Comment by vogtb** [comment]
`cellRangeValue("M1", "A1", "A2")`

Or instead of M1 use any value that isn't in A1:A2 inclusively.

When I wrote this a year ago, I didn't get to the point where you can query the sheet without binding values, so you can't access ranges from outside the sheet. but you could probably add it pretty easily if you wanted to. You'd just have to write an iterator that takes only a start and an end.

**Comment by MedinaGitHub** [comment]
it does not work =/
![image](https://user-images.githubusercontent.com/16387514/53768010-5571c480-3eb6-11e9-8ea3-d50207830a59.png)

but i'am confused...

in my node_ modules method is this
![image](https://user-images.githubusercontent.com/16387514/53768293-332c7680-3eb7-11e9-865d-25b82a330b38.png)

but is different to https://github.com/vogtb/spreadsheet/blob/master/dist/Sheet.js#L126

**Comment by MedinaGitHub** [comment]
I think I will not use cellRangeValue, better as you say, I will get the ranges by defining them in a cell. Thank you for answering my questions, sorry for the inconvenience, I only have one last question, do you know any way to import an excel file as an object of Sheet ()? to not pass all the excel by hand

**Comment by vogtb** [comment]
haha I don't know how to parse excel files, although there are node packages that can help. Good luck!

**Comment by MedinaGitHub** [comment]
Thanks You!
